name: Telegram Bot Runner
on:
  schedule:
    - cron: '*/30 * * * *'  # Menjalankan setiap 30 menit
  workflow_dispatch: # Menjalankan secara manual
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot
      - name: Run Telegram Bot
        run: |
          python bot.py
